Row entry box
brmighell/rcv-entry pull request #21
Opened 2021-10-29 16:47 UTC by fotakis08

2021-10-29 20:53 UTC, artoonie approved these changes
Tests would be nice too :)

2021-10-29 20:53 UTC, artoonie commented on data-table/table.js
> +// eslint-disable-next-line valid-jsdoc
Curious why the jsdoc isn't valid / can it be made valid?

2021-10-29 20:53 UTC, artoonie commented on data-table/table.js
> +// eslint-disable-next-line no-unused-vars
what is unused?

2021-10-29 20:53 UTC, artoonie commented on data-table/table.js
> +    }else {
[nit] add a space before `else`

2021-11-01 02:20 UTC, brmighell requested changes
Doesn't work yet - will re-review after pair programming on Nov. 1st

2021-11-05 15:04 UTC, closed without merging